export const UPDATE_MEDICAL_INFORMATION = 'UPDATE_MEDICAL_INFORMATION';
export const UPDATE_MEDICAL_INFORMATION_SUCCESS = 'UPDATE_MEDICAL_INFORMATION_SUCCESS';
export const UPDATE_MEDICAL_INFORMATION_ERROR = 'UPDATE_MEDICAL_INFORMATION_ERROR';
export const RESET_UPDATE_MEDICAL_INFORMATION = 'RESET_UPDATE_MEDICAL_INFORMATION';