export const POST_REGISTER = 'POST_REGISTER';
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS';
export const POST_REGISTER_ERROR = 'POST_REGISTER_ERROR';
export const RESET_POST_REGISTER = 'RESET_POST_REGISTER';