export const GET_PERSONAL_INFORMATION = 'GET_PERSONAL_INFORMATION';
export const GET_PERSONAL_INFORMATION_SUCCESS = 'GET_PERSONAL_INFORMATION_SUCCESS';
export const GET_PERSONAL_INFORMATION_ERROR = 'GET_PERSONAL_INFORMATION_ERROR';
export const RESET_PERSONAL_INFORMATION = 'RESET_PERSONAL_INFORMATION';
