export const UPDATE_REGISTERED_USER = 'UPDATE_REGISTERED_USER';
export const UPDATE_REGISTERED_USER_SUCCESS = 'UPDATE_REGISTERED_USER_SUCCESS';
export const UPDATE_REGISTERED_USER_ERROR = 'UPDATE_REGISTERED_USER_ERROR';
export const RESET_UPDATE_REGISTERED_USER = 'RESET_UPDATE_REGISTERED_USER';