export const GET_MEDICAL_INFORMATIONS = 'GET_MEDICAL_INFORMATIONS';
export const GET_MEDICAL_INFORMATIONS_SUCCESS = 'GET_MEDICAL_INFORMATIONS_SUCCESS';
export const GET_MEDICAL_INFORMATIONS_ERROR = 'GET_MEDICAL_INFORMATIONS_ERROR';
export const RESET_GET_MEDICAL_INFORMATIONS = 'RESET_GET_MEDICAL_INFORMATIONS';